name: Release Workflow

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write

jobs:

  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    needs: 
      - get-version 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

    - name: Install Trunk and wasm-bindgen
      run: cargo install trunk wasm-bindgen-cli

    - name: Build for release
      run: trunk build --release
    - name: Build
      env:
         VERSION: "${{ needs.get-version.outputs.version }}"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ get-version, build ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with: 
          path: build/
      - name: Create GitHub Release
        env:
          VERSION: "${{ needs.get-version.outputs.version }}"
          REPO: "${{ github.repository }}"
          COMMIT: "${{ github.sha }}"
          GH_TOKEN: "${{ github.token }}"
        run: |
          gh release create --repo $REPO --target $COMMIT $VERSION build/*
