name: Release Workflow

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write

jobs:

  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'
      prerelease-branches: '^(beta)$'

  build:
    name: Build for Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    needs: get-version
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      - name: trunk action
        uses: jetli/trunk-action@v0.5.0
        with: 
          version:
            latest

      - name: Build for release
        run: trunk build --release

      - name: Compress artifacts into a ZIP file
        run: zip -r build-${{ matrix.os }}.zip ./dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: build-${{ matrix.os }}.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [get-version, build]
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with: 
          path: ./dist/

      - name: Create GitHub Release
        env:
          CHANGELOG: "${{ needs.get-version.outputs.changelogs }}"
          VERSION: "${{ needs.get-version.outputs.version }}"
          REPO: "${{ github.repository }}"
          COMMIT: "${{ github.sha }}"
          GH_TOKEN: "${{ github.token }}"
        run: |
          echo "$CHANGELOG" > Changelog.md
          gh release create -F Changelog.md --repo $REPO --target $COMMIT $VERSION dist/build-*/build-*.zip
